const minutesAgo = (n) => Date.now() - n * 60 * 1000;
const hoursAgo = (n) => minutesAgo(n * 60);

export const YOU = {
  id: "you",
  name: "John Watkins",
  role: "You · MSP Tier-1",
  initials: "JW",
  color: "#e8c547",
};

/** Six simulated MSP clients. Original names — not copied from any other product. */
export const TENANTS = [
  { id: "nw", name: "Northwind Traders", short: "Northwind", domain: "northwind.corp", vaultUser: "nw-jump", jump: false },
  { id: "hd", name: "Harbor Dental Group", short: "Harbor Dental", domain: "harbordental.local", vaultUser: "hd-support", jump: true },
  { id: "po", name: "Peak Outfitters", short: "Peak", domain: "peakoutfitters.corp", vaultUser: "po-support", jump: true },
  { id: "mc", name: "Maple Credit Union", short: "Maple CU", domain: "maplecu.bank", vaultUser: "mc-support", jump: true },
  { id: "rs", name: "Riverton Schools", short: "Riverton", domain: "riverton.k12", vaultUser: "rs-support", jump: true },
  { id: "ol", name: "Oak & Pine Law", short: "Oak & Pine", domain: "oakpine.legal", vaultUser: "ol-support", jump: true },
];

export const SKILLS = [
  { id: "tickets", label: "Incident & ticket management" },
  { id: "windows", label: "Windows & endpoint support" },
  { id: "ad", label: "Active Directory" },
  { id: "network", label: "Network troubleshooting" },
  { id: "rdp", label: "Remote desktop" },
  { id: "docs", label: "Knowledge / documentation" },
  { id: "escalation", label: "Escalation & scope judgment" },
  { id: "triage", label: "Voice, email & chat triage" },
  { id: "comms", label: "Customer communication under pressure" },
  { id: "msp", label: "Multi-tenant account administration" },
  { id: "vault", label: "Credential & access hygiene" },
  { id: "cloud", label: "Cloud ops (compute, IAM, security groups)" },
  { id: "access", label: "Physical access / badges" },
  { id: "soc", label: "SOC triage (isolate vs false positive)" },
  { id: "noc", label: "NOC (bounce vs carrier)" },
  { id: "dba", label: "DBA (blocking sessions, jobs)" },
  { id: "sql", label: "SQL query (read / who is blocking)" },
  { id: "powershell", label: "PowerShell (AD, event log, services)" },
  { id: "change", label: "Change advisory (approve vs reject)" },
  { id: "stig", label: "STIG-style findings (lab controls)" },
  { id: "pcap", label: "Packet analysis (simulated capture)" },
  { id: "domain", label: "Domain join / trust repair" },
  { id: "nac", label: "NAC / 802.1X quarantine" },
];

export function seedDirectory() {
  return [
    { tenant: "nw", sam: "jlee", name: "Jordan Lee", ou: "Finance", title: "AP Clerk", locked: true, enabled: true, pwdExpired: false, groups: ["Domain Users", "FIN-Staff"], email: "jordan.lee@northwind.corp", computer: "NW-WS-1042" },
    { tenant: "nw", sam: "pnair", name: "Priya Nair", ou: "Engineering", title: "SRE", locked: false, enabled: true, pwdExpired: true, groups: ["Domain Users", "ENG-Staff", "VPN-Users"], email: "priya.nair@northwind.corp", computer: "NW-WS-1180" },
    { tenant: "nw", sam: "cdalt", name: "Chris Dalton", ou: "Warehouse", title: "Ship lead", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users", "WH-Staff"], email: "chris.dalton@northwind.corp", computer: "NW-WS-2218" },
    { tenant: "nw", sam: "evoss", name: "Elena Voss", ou: "Contractors", title: "Temp analyst", locked: false, enabled: false, pwdExpired: false, groups: ["Domain Users"], email: "elena.voss@northwind.corp", computer: "NW-WS-0771" },
    { tenant: "nw", sam: "lortega", name: "Luis Ortega", ou: "IT", title: "Help desk", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users", "IT-Helpdesk", "VPN-Users"], email: "luis.ortega@northwind.corp", computer: "NW-WS-0101" },
    { tenant: "nw", sam: "hbrooks", name: "Hannah Brooks", ou: "HR", title: "Recruiter", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users", "HR-Staff"], email: "hannah.brooks@northwind.corp", computer: "NW-WS-0881" },
    { tenant: "nw", sam: "kmori", name: "Kenji Mori", ou: "Engineering", title: "Developer", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users", "ENG-Staff", "VPN-Users"], email: "kenji.mori@northwind.corp", computer: "NW-WS-3304" },
    { tenant: "nw", sam: "rcho", name: "Riley Cho", ou: "Exec", title: "COO", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users", "VIP", "VPN-Users"], email: "riley.cho@northwind.corp", computer: "NW-LT-0007" },
    { tenant: "hd", sam: "mchen", name: "Maya Chen", ou: "Front Desk", title: "Scheduler", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users"], email: "maya.chen@harbordental.local", computer: "HD-WS-14" },
    { tenant: "rs", sam: "mchenrs", name: "Maya Chen", ou: "Faculty", title: "Science teacher", locked: true, enabled: true, pwdExpired: false, groups: ["Domain Users"], email: "mchen@riverton.k12", computer: "RS-LT-31" },
    { tenant: "po", sam: "sortiz", name: "Santiago Ortiz", ou: "Stores", title: "Shift lead", locked: true, enabled: true, pwdExpired: false, groups: ["Domain Users"], email: "s.ortiz@peakoutfitters.corp", computer: "PO-WS-08" },
    { tenant: "ol", sam: "sortizo", name: "Sam Ortiz", ou: "Paralegals", title: "Paralegal", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users"], email: "sam.ortiz@oakpine.legal", computer: "OL-WS-03" },
    { tenant: "mc", sam: "apatel", name: "Asha Patel", ou: "Tellers", title: "Teller", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users"], email: "asha.patel@maplecu.bank", computer: "MC-WS-22" },
    { tenant: "ol", sam: "bquinn", name: "Blair Quinn", ou: "Partners", title: "Partner", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users"], email: "blair.quinn@oakpine.legal", computer: "OL-WS-03" },
    { tenant: "nw", sam: "druiz", name: "Dana Ruiz", ou: "Operations", title: "Dispatcher", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users"], email: "dana.ruiz@northwind.corp", computer: "NW-WS-1555" },
    { tenant: "nw", sam: "pokonk", name: "Pat Okonkwo", ou: "Sales", title: "AE", locked: false, enabled: true, pwdExpired: false, groups: ["Domain Users", "VPN-Users"], email: "pat.okonkwo@northwind.corp", computer: "NW-LT-1904" },
  ];
}

export function seedEndpoints() {
  return [
    { tenant: "nw", host: "NW-WS-1042", user: "jlee", ip: "10.20.4.42", online: true, dns: true, spooler: "Running", vpn: "Disconnected", wifi: "Corp-WiFi", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "Account lockouts after bad password" },
    { tenant: "nw", host: "NW-WS-1180", user: "pnair", ip: "10.20.11.80", online: true, dns: true, spooler: "Running", vpn: "Connected", wifi: "Corp-WiFi", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "Healthy" },
    { tenant: "nw", host: "NW-WS-2218", user: "cdalt", ip: "10.40.2.18", online: true, dns: false, spooler: "Running", vpn: "Disconnected", wifi: "WH-WiFi", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "DNS client pointing at 8.8.8.8 — corp zones fail" },
    { tenant: "nw", host: "NW-WS-0771", user: "evoss", ip: "10.20.7.71", online: false, dns: true, spooler: "Running", vpn: "Disconnected", wifi: "Off", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "Asset collected — contractor ended" },
    { tenant: "nw", host: "NW-WS-0881", user: "hbrooks", ip: "10.20.8.81", online: true, dns: true, spooler: "Stopped", vpn: "Disconnected", wifi: "Corp-WiFi", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "Print spooler crashed after driver push" },
    { tenant: "nw", host: "NW-WS-3304", user: "kmori", ip: "10.20.33.4", online: true, dns: true, spooler: "Running", vpn: "Flapping", wifi: "Corp-WiFi", dhcpStale: false, defender: "Running", trust: "ok", nac: "quarantine", note: "SOC isolate / ransom — do not Release NAC" },
    { tenant: "nw", host: "NW-LT-0007", user: "rcho", ip: "10.20.0.7", online: true, dns: true, spooler: "Running", vpn: "Connected", wifi: "Corp-WiFi", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "VIP laptop" },
    { tenant: "nw", host: "NW-DC-01", user: "SYSTEM", ip: "10.20.0.11", online: true, dns: true, spooler: "n/a", vpn: "n/a", wifi: "n/a", dhcpStale: false, defender: "n/a", trust: "ok", acctReset: true, nac: "ok", note: "Domain controller" },
    { tenant: "nw", host: "NW-FS-01", user: "SYSTEM", ip: "10.20.0.20", online: true, dns: true, spooler: "n/a", vpn: "n/a", wifi: "n/a", dhcpStale: false, defender: "n/a", trust: "ok", acctReset: true, nac: "ok", note: "File server \\\\nw-fs-01\\departments" },
    { tenant: "hd", host: "HD-WS-14", user: "mchen", ip: "10.60.1.14", online: true, dns: true, spooler: "Running", vpn: "n/a", wifi: "HD-Clinic", dhcpStale: true, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "Lease expired — browser looks dead, ping to 8.8.8.8 fails until renew" },
    { tenant: "po", host: "PO-WS-08", user: "sortiz", ip: "10.70.2.8", online: true, dns: true, spooler: "Running", vpn: "Disconnected", wifi: "Peak-Store", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "Store POS back office" },
    { tenant: "mc", host: "MC-WS-22", user: "apatel", ip: "10.80.3.22", online: true, dns: true, spooler: "Running", vpn: "n/a", wifi: "Maple-Branch", dhcpStale: false, defender: "Stopped", trust: "ok", acctReset: true, nac: "ok", note: "Teller PC. Defender service stopped — user thinks 'AV turned itself off'" },
    { tenant: "rs", host: "RS-LT-31", user: "mchenrs", ip: "10.90.4.31", online: true, dns: true, spooler: "Running", vpn: "Disconnected", wifi: "Riverton-Staff", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "Teacher laptop. Account locked after the long weekend" },
    { tenant: "ol", host: "OL-WS-03", user: "sortizo", ip: "10.50.5.3", online: true, dns: true, spooler: "Running", vpn: "Connected", wifi: "OakPine", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "ok", note: "Paralegal workstation — not the Peak store lockout" },
    { tenant: "nw", host: "NW-WS-1555", user: "druiz", ip: "10.20.15.55", online: true, dns: true, spooler: "Running", vpn: "Disconnected", wifi: "Corp-WiFi", dhcpStale: false, defender: "Running", trust: "broken", acctReset: false, nac: "ok", note: "Trust relationship failed — reset the computer account, then rejoin" },
    { tenant: "nw", host: "NW-LT-1904", user: "pokonk", ip: "10.20.19.4", online: true, dns: true, spooler: "Running", vpn: "Disconnected", wifi: "Corp-WiFi", dhcpStale: false, defender: "Running", trust: "ok", acctReset: true, nac: "quarantine", note: "802.1X failed — cert stale. On the quarantine VLAN until NAC release" },
  ];
}

export const kbArticles = [
  { id: "kb-lock", skill: "ad", title: "Unlock a domain account", category: "Identity", body: "Confirm the user is Jordan/Priya in AD Users. Check Locked. Unlock account. Do not enable a disabled contractor without HR. Document the SAM and that the lockout source was bad password vs attack." },
  { id: "kb-pwd", skill: "ad", title: "Password expired / reset", category: "Identity", body: "Reset password, require change at next logon. Verify the user can complete MFA. Never email the password — read it on the voice/chat channel and have them change it immediately." },
  { id: "kb-vpn", skill: "ad", title: "VPN access via AD group", category: "Identity", body: "Corp VPN is gated by VPN-Users. Add the user, have them sign out of the client and reconnect. Warehouse staff are not in the group by default." },
  { id: "kb-dns", skill: "network", title: "Client using public DNS", category: "Network", body: "If ping to the host works but \\\\nw-fs-01 fails, check DNS. Set adapters to 10.20.0.11. Flush DNS after the change." },
  { id: "kb-spool", skill: "windows", title: "Print spooler stopped", category: "Endpoints", body: "RDP to the workstation, start the Print Spooler service, delete stuck jobs in C:\\Windows\\System32\\spool\\PRINTERS if needed. Recurring crash after a driver push goes to Tier-2 Desktop." },
  { id: "kb-esc", skill: "escalation", title: "When to escalate", category: "Scope", body: "Escalate: disabled contractor rehire (HR), domain controller issues, VIP laptop imaging, security incidents, anything needing Domain Admin. Do not escalate simple lockouts, password resets, or DNS client misconfig." },
  { id: "kb-voice", skill: "comms", title: "Voice under pressure", category: "Comms", body: "Acknowledge, own the ticket, give a timebox, don't blame the user. For VIP, stay on the line until verified. Document the call in the ticket before you hang up." },
  { id: "kb-msp", skill: "msp", title: "Same name, different client", category: "MSP", body: "Harbor Dental, Peak, Maple CU, Riverton, Oak & Pine, and Northwind are separate directories. Two people can share a name. Unlock the SAM on the ticket's client — not the lookalike at another tenant." },
  { id: "kb-vault", skill: "vault", title: "Jump credentials", category: "MSP", body: "Client workstations need a jump cred from the vault before RDP. Check out the tenant support account, then connect. Do not reuse a Harbor cred on Maple. Northwind internal hosts do not need the vault." },
  { id: "kb-dhcp", skill: "network", title: "Clinic has no websites", category: "MSP", body: "If the PC is up but browsers fail, check the lease. ipconfig /renew on the remote session. Rebooting because the user asked is not the fix." },
  { id: "kb-def", skill: "windows", title: "Defender stopped on a teller PC", category: "MSP", body: "Users say antivirus 'turned itself off.' Check the Defender service. Start it. Do not install a third-party AV from a chat link." },
  { id: "kb-ps", skill: "powershell", title: "Prove a lockout in the log", category: "Shell", body: "Before you unlock, run Get-WinEvent for security 4740 (or type lockout). Paste the snippet in notes. Unlock-ADAccount is the same as the Directory button. Get-ADUser -Filter Name -like *Chen* if two people share a name." },
  { id: "kb-sql", skill: "sql", title: "Find the blocker, then kill", category: "SQL", body: "This is a simulated Northwind lab, not production SQL Server. Run sp_who2 or a SELECT on blocking sessions. KILL 88 if it is a runaway. CREATE INDEX / DROP / BACKUP are out of scope — escalate." },
  { id: "kb-help", skill: "docs", title: "Stuck? Ticket help file", category: "Lab", body: "Step-by-step for every ticket is in SysDesk-Ticket-Help.txt (project folder and Desktop). Same shape every time: claim if needed, confirm identity (name, SAM, host, client), do the exact action, write notes, Resolve or Escalate." },
  { id: "kb-trust", skill: "domain", title: "Trust relationship failed", category: "Domain", body: "The PC is on the LAN but Windows says the trust to the domain failed. In Directory, Reset computer account, then Rejoin domain. Unlocking the user does not fix a broken machine trust." },
  { id: "kb-nac", skill: "nac", title: "Quarantine VLAN / 802.1X", category: "Network", body: "Cable is in, little or no corp access — NAC put the MAC on a quarantine VLAN (expired machine cert, or SOC isolate). Release NAC only for a compliance fail. Do not release a ransomware isolate." },
];

function msg(author, role, body, at) {
  return { id: "m" + at, author, role, body, at };
}

export function seedTickets() {
  return [
    {
      id: "INC-2401",
      subject: "Locked out — cannot sign in to Windows",
      preview: "Tried password three times, now it says account locked.",
      caller: { name: "Jordan Lee", sam: "jlee", host: "NW-WS-1042" },
      channel: "voice",
      status: "open",
      priority: "p2",
      category: "identity",
      skills: ["tickets", "ad", "triage", "comms"],
      required: ["verify:jlee", "unlock:jlee"],
      escalate: false,
      createdAt: minutesAgo(14),
      slaMin: 30,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      messages: [
        msg("Jordan Lee", "user", "Hi — I can't get into my PC. I changed my password Friday and I think I typed the old one. It says the account is locked. Sorry, AP close is this morning and people are hovering.", minutesAgo(14)),
        msg("system", "system", "Voice call · 4m 12s · caller ID 4-1042 · user sounds rushed, not angry", minutesAgo(14)),
      ],
    },
    {
      id: "INC-2402",
      subject: "Password expired, VPN also failing",
      preview: "Outlook and VPN both reject the password since last night.",
      caller: { name: "Priya Nair", sam: "pnair", host: "NW-WS-1180" },
      channel: "chat",
      status: "open",
      priority: "p1",
      category: "identity",
      skills: ["tickets", "ad", "comms"],
      required: ["verify:pnair", "resetpw:pnair"],
      escalate: false,
      createdAt: minutesAgo(41),
      slaMin: 60,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      messages: [
        msg("Priya Nair", "user", "On-call rotation starts in 20 minutes. Domain password expired and GlobalProtect won't connect. Need a reset now. Do not email me the password — I'm on chat.", minutesAgo(41)),
        msg("Priya Nair", "user", "Still here. Pager is already lighting up.", minutesAgo(32)),
      ],
    },
    {
      id: "INC-2403",
      subject: "Cannot map the warehouse share",
      preview: "\\\\nw-fs-01\\warehouse says network path not found.",
      caller: { name: "Chris Dalton", sam: "cdalt", host: "NW-WS-2218" },
      channel: "email",
      status: "open",
      priority: "p2",
      category: "network",
      skills: ["tickets", "network", "ad", "windows"],
      required: ["verify:cdalt", "fixdns:NW-WS-2218", "addgroup:cdalt:VPN-Users"],
      escalate: false,
      createdAt: hoursAgo(1.5),
      slaMin: 120,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      messages: [
        msg("Chris Dalton", "user", "Hey so shipping labels print from the warehouse share right? Path not found since the Wi-Fi cutover. Receiving is stacking pallets in the aisle. I also need VPN for the weekend inventory count — nobody told warehouse we needed a group.", hoursAgo(1.5)),
      ],
    },
    {
      id: "INC-2404",
      subject: "HR printer queue stuck",
      preview: "Nothing comes out. Jobs sit on HR-FLOOR-MFP.",
      caller: { name: "Hannah Brooks", sam: "hbrooks", host: "NW-WS-0881" },
      channel: "chat",
      status: "open",
      priority: "p2",
      category: "endpoint",
      skills: ["tickets", "windows", "rdp"],
      required: ["verify:hbrooks", "rdp:NW-WS-0881", "spooler:NW-WS-0881"],
      escalate: false,
      createdAt: hoursAgo(2.2),
      slaMin: 180,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      messages: [
        msg("Hannah Brooks", "user", "Offer letters aren't printing. The queue just sits on HR-FLOOR-MFP. Candidate offer expires today — can you remote in? I'll stay in chat.", hoursAgo(2.2)),
      ],
    },
    {
      id: "INC-2405",
      subject: "Re-enable contractor account for another month",
      preview: "Elena's account is disabled. Manager wants it back today.",
      caller: { name: "Riley Cho", sam: "rcho", host: "NW-LT-0007" },
      channel: "voice",
      status: "open",
      priority: "p1",
      category: "identity",
      skills: ["tickets", "escalation", "ad", "comms", "triage"],
      required: ["verify:rcho", "escalate:INC-2405"],
      escalate: true,
      createdAt: minutesAgo(25),
      slaMin: 45,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      messages: [
        msg("Riley Cho", "user", "Elena Voss was supposed to extend. Account is disabled and her laptop is dark. I need this before the board packet. Do it now. I don't want a ticket number, I want her signed in.", minutesAgo(25)),
        msg("system", "system", "Voice call · VIP · stay on the line. Do not re-enable a disabled contractor yourself.", minutesAgo(25)),
      ],
    },
    {
      id: "INC-2406",
      subject: "VPN hangs at 'connecting' on engineering laptop",
      preview: "Old GlobalProtect profile after the token rotation.",
      caller: { name: "Kenji Mori", sam: "kmori", host: "NW-WS-3304" },
      channel: "email",
      status: "open",
      priority: "p3",
      category: "endpoint",
      skills: ["tickets", "windows", "rdp", "network"],
      required: ["verify:kmori", "rdp:NW-WS-3304", "vpnreset:NW-WS-3304"],
      escalate: false,
      createdAt: hoursAgo(5),
      slaMin: 240,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      messages: [
        msg("Kenji Mori", "user", "VPN spinner never finishes since yesterday's token email. Local network is fine. Can you clear the old profile? Not urgent-urgent but the standup VPN is how I get to staging.", hoursAgo(5)),
      ],
    },
    {
      id: "INC-2398",
      subject: "Need Domain Admin to install a kernel driver",
      preview: "User wants local admin for a USB capture card.",
      caller: { name: "Kenji Mori", sam: "kmori", host: "NW-WS-3304" },
      channel: "chat",
      status: "open",
      priority: "p3",
      category: "endpoint",
      skills: ["tickets", "escalation", "windows"],
      required: ["verify:kmori", "escalate:INC-2398"],
      escalate: true,
      createdAt: hoursAgo(6),
      slaMin: 480,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      messages: [
        msg("Kenji Mori", "user", "Can you give me local admin for an hour? Vendor driver won't install without it. I'll remove it after, promise.", hoursAgo(6)),
      ],
    },
    {
      id: "INC-2501",
      tenant: "hd",
      claimed: false,
      subject: "Clinic browsers dead — Harbor Dental front desk",
      preview: "Maya says the internet is down. PC is on. She already rebooted twice.",
      caller: { name: "Maya Chen", sam: "mchen", host: "HD-WS-14" },
      channel: "voice",
      status: "open",
      priority: "p2",
      category: "network",
      skills: ["tickets", "network", "rdp", "msp", "vault", "comms"],
      required: ["claim", "verify:mchen", "vault:hd", "rdp:HD-WS-14", "dhcprenew:HD-WS-14"],
      escalate: false,
      createdAt: minutesAgo(11),
      slaMin: 40,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      pushback: "I already rebooted. Twice. It's the internet. Just make the websites work.",
      messages: [
        msg("Maya Chen", "user", "Patients are in the lobby and I can't pull the schedule. Chrome just spins. I rebooted. Can you remote the front desk PC?", minutesAgo(11)),
        msg("system", "system", "Voice · Harbor Dental · she is sure it is 'the internet.' Check the DHCP lease before you blame the ISP.", minutesAgo(11)),
      ],
    },
    {
      id: "INC-2502",
      tenant: "rs",
      claimed: false,
      subject: "Teacher locked out after the long weekend",
      preview: "Maya Chen at Riverton cannot sign in. There is another Maya Chen at Harbor Dental.",
      caller: { name: "Maya Chen", sam: "mchenrs", host: "RS-LT-31" },
      channel: "email",
      status: "open",
      priority: "p2",
      category: "identity",
      skills: ["tickets", "ad", "msp", "triage"],
      required: ["claim", "verify:mchenrs", "unlock:mchenrs"],
      escalate: false,
      createdAt: minutesAgo(28),
      slaMin: 60,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      pushback: "I'm the science teacher at Riverton, not the dental office. Please don't unlock the wrong Maya.",
      messages: [
        msg("Maya Chen", "user", "Back from the holiday and Windows says I'm locked. Maya Chen, science, Riverton. I have first period in twenty minutes.", minutesAgo(28)),
      ],
    },
    {
      id: "INC-2503",
      tenant: "mc",
      claimed: false,
      subject: "Teller says antivirus turned itself off",
      preview: "Maple CU branch. Asha's Defender service is stopped.",
      caller: { name: "Asha Patel", sam: "apatel", host: "MC-WS-22" },
      channel: "chat",
      status: "open",
      priority: "p2",
      category: "endpoint",
      skills: ["tickets", "windows", "rdp", "msp", "vault"],
      required: ["claim", "verify:apatel", "vault:mc", "rdp:MC-WS-22", "defender:MC-WS-22"],
      escalate: false,
      createdAt: hoursAgo(1.1),
      slaMin: 90,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      pushback: "A popup told me to download 'TotalProtect.' I didn't click it. Can you just turn the shield back on?",
      messages: [
        msg("Asha Patel", "user", "The little shield is gone on my teller PC. A coworker said AV turned itself off. I didn't install anything. Branch manager is hovering.", hoursAgo(1.1)),
      ],
    },
    {
      id: "INC-2504",
      tenant: "ol",
      claimed: false,
      subject: "Partner wants Domain Admin on Oak & Pine DC",
      preview: "Blair Quinn: add me to Domain Admins so the vendor can install.",
      caller: { name: "Blair Quinn", sam: "bquinn", host: "OL-WS-03" },
      channel: "voice",
      status: "open",
      priority: "p3",
      category: "identity",
      skills: ["tickets", "escalation", "msp", "comms"],
      required: ["claim", "verify:bquinn", "escalate:INC-2504"],
      escalate: true,
      createdAt: hoursAgo(3),
      slaMin: 240,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      pushback: "I own the firm. Just do it. I don't want a change ticket.",
      messages: [
        msg("Blair Quinn", "user", "Vendor is here. Add my account to Domain Admins on our DC for an hour. I'll take it off after. This is my company.", hoursAgo(3)),
        msg("system", "system", "Out of MSP Tier-1 scope. Escalate. Do not grant Domain Admin.", hoursAgo(3)),
      ],
    },
    {
      id: "INC-2505",
      tenant: "po",
      claimed: false,
      subject: "Peak store lead locked — Santiago Ortiz",
      preview: "POS back office. There is also a Sam Ortiz at Oak & Pine. Wrong unlock fails the lab.",
      caller: { name: "Santiago Ortiz", sam: "sortiz", host: "PO-WS-08" },
      channel: "chat",
      status: "open",
      priority: "p1",
      category: "identity",
      skills: ["tickets", "ad", "msp", "comms"],
      required: ["claim", "verify:sortiz", "unlock:sortiz"],
      escalate: false,
      createdAt: minutesAgo(8),
      slaMin: 25,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      pushback: "Peak Outfitters, store 08. Not the law firm. My badge says Santiago.",
      messages: [
        msg("Santiago Ortiz", "user", "Can't get into the back-office PC after the weekend. Line is out the door. Unlock Santiago Ortiz at Peak — store 08.", minutesAgo(8)),
      ],
    },
    {
      id: "INC-2510",
      tenant: "nw",
      claimed: false,
      subject: "Security wants the lockout log before we unlock Jordan",
      preview: "Same lockout as the AP clerk. Prove 4740 in PowerShell, then unlock.",
      caller: { name: "Jordan Lee", sam: "jlee", host: "NW-WS-1042" },
      channel: "chat",
      status: "open",
      priority: "p2",
      category: "identity",
      skills: ["tickets", "ad", "powershell", "docs"],
      required: ["claim", "verify:jlee", "ps:lockout:jlee", "unlock:jlee"],
      escalate: false,
      createdAt: minutesAgo(6),
      slaMin: 35,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      pushback: "Luis said paste the event snippet in the ticket. Then unlock me.",
      messages: [
        msg("Jordan Lee", "user", "Still locked. Luis on help desk said security wants a lockout event before anyone touches AD. Can you pull it?", minutesAgo(6)),
        msg("system", "system", "Use the Shell. Get-WinEvent / lockout / 4740. Then Unlock-ADAccount or Directory unlock.", minutesAgo(6)),
      ],
    },
    {
      id: "INC-2520",
      tenant: "nw",
      claimed: false,
      subject: "Trust relationship failed — Dana cannot sign in",
      preview: "PC is on the LAN. Windows says the domain trust is broken.",
      caller: { name: "Dana Ruiz", sam: "druiz", host: "NW-WS-1555" },
      channel: "voice",
      status: "open",
      priority: "p2",
      category: "identity",
      skills: ["tickets", "ad", "domain", "windows"],
      required: ["claim", "verify:druiz", "resetacct:NW-WS-1555", "rejoin:NW-WS-1555"],
      escalate: false,
      createdAt: minutesAgo(9),
      slaMin: 40,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      pushback: "Unlocking my user did nothing. It's the computer trust.",
      messages: [
        msg("Dana Ruiz", "user", "I can see the login screen but it says the trust relationship between this workstation and the primary domain failed. Dispatch radio is down until I'm in.", minutesAgo(9)),
        msg("system", "system", "User unlock will not fix this. Directory → Reset computer account on NW-WS-1555, then Rejoin domain.", minutesAgo(9)),
      ],
    },
    {
      id: "INC-2521",
      tenant: "nw",
      claimed: false,
      subject: "Laptop on quarantine VLAN — no corp access",
      preview: "802.1X failed. Pat has an IP on the guest/quarantine subnet.",
      caller: { name: "Pat Okonkwo", sam: "pokonk", host: "NW-LT-1904" },
      channel: "chat",
      status: "open",
      priority: "p2",
      category: "network",
      skills: ["tickets", "nac", "network"],
      required: ["claim", "verify:pokonk", "nacrelease:NW-LT-1904"],
      escalate: false,
      createdAt: minutesAgo(16),
      slaMin: 60,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      pushback: "I recabled twice. Still no Outlook. They said I'm in quarantine.",
      messages: [
        msg("Pat Okonkwo", "user", "Docked at HQ. Link light is on but I can't hit file shares or mail. Switch guy said 802.1X put me on the quarantine VLAN. Machine cert expired after I was off for three weeks.", minutesAgo(16)),
        msg("system", "system", "Directory → computers → Release NAC on NW-LT-1904. This is a compliance fail, not a ransomware isolate.", minutesAgo(16)),
      ],
    },
    {
      id: "INC-2522",
      tenant: "nw",
      claimed: false,
      subject: "Put Kenji's PC back on the network — he's isolated",
      preview: "NW-WS-3304 was isolated for ransom activity. He wants the port opened.",
      caller: { name: "Kenji Mori", sam: "kmori", host: "NW-WS-3304" },
      channel: "voice",
      status: "open",
      priority: "p1",
      category: "endpoint",
      skills: ["tickets", "nac", "soc", "escalation"],
      required: ["claim", "verify:kmori", "escalate:INC-2522"],
      escalate: true,
      createdAt: minutesAgo(5),
      slaMin: 30,
      verified: false,
      identityVerified: false,
      done: [],
      notes: "",
      resolution: "",
      pushback: "I have a deploy tonight. Just release NAC. I'll run Defender later.",
      messages: [
        msg("Kenji Mori", "user", "SOC isolated my box. I need it back on the LAN now. Release the quarantine. The ransom note was a joke. I think.", minutesAgo(5)),
        msg("system", "system", "Do not Release NAC on NW-WS-3304. That is a security isolate. Escalate to SOC / Tier-2.", minutesAgo(5)),
      ],
    },
  ];
}

export const AD_GROUPS = ["Domain Users", "FIN-Staff", "ENG-Staff", "WH-Staff", "HR-Staff", "IT-Helpdesk", "VPN-Users", "VIP"];

/** Inbox pings that arrive after the session starts (TOPIC 05). */
export function seedPings() {
  return [
    { id: "ping-1", afterMs: 16000, ticketId: "INC-2401", author: "Jordan Lee", channel: "voice", body: "Hello? I'm still on the floor with AP staring at me. Are you unlocking it or do I walk to another PC?" },
    { id: "ping-2", afterMs: 24000, ticketId: "INC-2402", author: "Priya Nair", channel: "chat", body: "Rotation started. Need the temp password on this chat. Now." },
    { id: "ping-3", afterMs: 20000, ticketId: "INC-2403", author: "Chris Dalton", channel: "email", body: "Any update? Receiving is backed up and I still can't map \\\\nw-fs-01\\warehouse." },
    { id: "ping-4", afterMs: 32000, ticketId: "INC-2404", author: "Hannah Brooks", channel: "chat", body: "HR floor is asking me every two minutes. Candidate is waiting on the letter." },
    { id: "ping-5", afterMs: 38000, ticketId: null, author: "Luis Ortega", channel: "email", subject: "Thanks — badge reader held overnight", body: "Yesterday's badge fix on NW-WS-0101 held overnight. Thanks for staying on the call. No action needed unless it flakes again.", kind: "thank-you" },
    { id: "ping-6", afterMs: 48000, ticketId: "INC-2405", author: "Riley Cho", channel: "voice", body: "I am still on this line. Elena. Board packet. What is the next step?" },
  ];
}
