function minutesAgo(n) {
  return Date.now() - n * 60 * 1000;
}

function hoursAgo(n) {
  return minutesAgo(n * 60);
}

function msg(author, role, body, at) {
  return { id: "m" + at + Math.random().toString(16).slice(2), author, role, body, at };
}

function baseTicket(t) {
  return {
    status: "open",
    verified: false,
    identityVerified: false,
    done: [],
    notes: "",
    resolution: "",
    escalate: false,
    slaMin: 120,
    ...t,
  };
}

export function seedCloud() {
  return {
    vms: [
      { id: "i-0webprod", name: "web-prod", az: "us-east-1a", state: "stopped", type: "t3.large", disk: "42%", sg: "sg-web" },
      { id: "i-0batch01", name: "batch-jobs", az: "us-east-1b", state: "running", type: "t3.xlarge", disk: "97%", sg: "sg-batch" },
      { id: "i-0bastion", name: "bastion", az: "us-east-1a", state: "running", type: "t3.micro", disk: "18%", sg: "sg-bastion" },
    ],
    iam: [
      { user: "deploy-bot", mfa: true, keys: [{ id: "AKIA-OLD1", status: "Active", leaked: true }], last: "CLI from 185.12.9.4" },
      { user: "pnair", mfa: true, keys: [{ id: "AKIA-PN01", status: "Active", leaked: false }], last: "console" },
      { user: "contractor-evoss", mfa: false, keys: [{ id: "AKIA-EV01", status: "Active", leaked: false }], last: "never" },
    ],
    sgs: [
      { id: "sg-web", name: "web-prod", rules: [{ proto: "tcp", port: "443", cidr: "0.0.0.0/0", ok: true }, { proto: "tcp", port: "22", cidr: "0.0.0.0/0", ok: false }] },
      { id: "sg-bastion", name: "bastion", rules: [{ proto: "tcp", port: "22", cidr: "10.20.0.0/16", ok: true }] },
      { id: "sg-batch", name: "batch-jobs", rules: [{ proto: "tcp", port: "1433", cidr: "10.20.0.0/16", ok: true }] },
    ],
    tickets: [
      baseTicket({
        id: "CLD-1001",
        desk: "cloud",
        subject: "web-prod is down — site 502",
        preview: "Instance stopped after last night's patch window.",
        caller: { name: "Priya Nair", sam: "pnair", host: "web-prod" },
        channel: "chat",
        priority: "p1",
        category: "compute",
        skills: ["tickets"],
        skills: ["tickets", "cloud"],
        required: ["verify:pnair", "start:web-prod"],
        labHint: "Site is 502 because web-prod is stopped. Confirm identity, then Start that instance. Leave IAM and SSH alone.",
        createdAt: minutesAgo(22),
        slaMin: 45,
        messages: [msg("Priya Nair", "user", "storefront is 502. EC2 web-prod shows stopped. We did not stop it. Can you start it and tell me why it died?", minutesAgo(22))],
      }),
      baseTicket({
        id: "CLD-1002",
        desk: "cloud",
        subject: "GitHub alert: deploy-bot access key on GitHub",
        preview: "Secret scanning hit AKIA-OLD1 in a public gist.",
        caller: { name: "Kenji Mori", sam: "kmori", host: "deploy-bot" },
        channel: "email",
        priority: "p1",
        category: "iam",
        skills: ["tickets", "cloud", "escalation"],
        required: ["verify:kmori", "disablekey:AKIA-OLD1"],
        labHint: "A deploy-bot key leaked on GitHub. Confirm identity, then Disable AKIA-OLD1. Do not start VMs or change SSH.",
        createdAt: minutesAgo(40),
        slaMin: 30,
        messages: [msg("Kenji Mori", "user", "GitHub emailed us. deploy-bot key is in a gist. Disable it. Do not rotate in chat — just kill the key and I'll cut a new one in secrets manager.", minutesAgo(40))],
      }),
      baseTicket({
        id: "CLD-1003",
        desk: "cloud",
        subject: "SSH open to the world on web-prod",
        preview: "sg-web allows 22 from 0.0.0.0/0. Audit finding.",
        caller: { name: "Luis Ortega", sam: "lortega", host: "sg-web" },
        channel: "email",
        priority: "p2",
        category: "network",
        skills: ["tickets", "cloud"],
        required: ["verify:lortega", "lockssh:sg-web"],
        labHint: "sg-web allows SSH from the internet. Confirm identity, then Lock SSH. Do not disable keys or start instances.",
        createdAt: hoursAgo(3),
        slaMin: 240,
        messages: [msg("Luis Ortega", "user", "Weekly CIS scan: web-prod security group has SSH from the internet. Restrict 22 to the bastion SG or 10.20.0.0/16.", hoursAgo(3))],
      }),
    ],
  };
}

export function seedAccess() {
  return {
    doors: [
      { id: "WH-DOCK", name: "Warehouse dock", controller: "CTRL-04", online: true, grant: "WH-Staff" },
      { id: "HR-SUITE", name: "HR suite", controller: "CTRL-02", online: true, grant: "HR-Staff" },
      { id: "DC-CAGE", name: "Data center cage", controller: "CTRL-01", online: true, grant: "IT-Helpdesk" },
      { id: "EXEC-FL", name: "Exec floor", controller: "CTRL-07", online: false, grant: "VIP" },
    ],
    badges: [
      { id: "B-4412", name: "Chris Dalton", sam: "cdalt", status: "active", doors: [] },
      { id: "B-1088", name: "Hannah Brooks", sam: "hbrooks", status: "active", doors: ["HR-SUITE"] },
      { id: "B-0771", name: "Elena Voss", sam: "evoss", status: "active", doors: ["HR-SUITE", "WH-DOCK"] },
      { id: "B-0007", name: "Riley Cho", sam: "rcho", status: "active", doors: ["EXEC-FL", "HR-SUITE"] },
    ],
    tickets: [
      baseTicket({
        id: "ACS-2001",
        desk: "access",
        subject: "Dock door denies Chris after shift change",
        preview: "Badge B-4412 beeps red at WH-DOCK. Worked yesterday.",
        caller: { name: "Chris Dalton", sam: "cdalt", host: "WH-DOCK" },
        channel: "voice",
        priority: "p2",
        category: "badge",
        skills: ["tickets", "access"],
        required: ["verify:cdalt", "grantdoor:B-4412:WH-DOCK"],
        createdAt: minutesAgo(18),
        messages: [msg("Chris Dalton", "user", "Dock reader went red this morning. Same badge. Trucks are in the yard. Can you add Warehouse dock back to my badge?", minutesAgo(18))],
      }),
      baseTicket({
        id: "ACS-2002",
        desk: "access",
        subject: "Exec floor controller offline",
        preview: "CTRL-07 last seen 47 minutes ago. Riley stuck at the elevator.",
        caller: { name: "Riley Cho", sam: "rcho", host: "CTRL-07" },
        channel: "voice",
        priority: "p1",
        category: "controller",
        skills: ["tickets", "access"],
        required: ["verify:rcho", "rebootctrl:CTRL-07"],
        createdAt: minutesAgo(47),
        slaMin: 40,
        messages: [msg("Riley Cho", "user", "Elevator badge to exec is dead. I have a vendor in the lobby. Reboot the controller. Do not tell me to walk the stairs in these shoes.", minutesAgo(47))],
      }),
      baseTicket({
        id: "ACS-2003",
        desk: "access",
        subject: "Contractor badge still opens HR after term",
        preview: "Elena Voss disabled in AD. Badge B-0771 still active.",
        caller: { name: "Hannah Brooks", sam: "hbrooks", host: "B-0771" },
        channel: "email",
        priority: "p1",
        category: "identity",
        skills: ["tickets", "access", "escalation"],
        required: ["verify:hbrooks", "disablebadge:B-0771"],
        escalate: false,
        createdAt: hoursAgo(2),
        slaMin: 60,
        messages: [msg("Hannah Brooks", "user", "Elena's Windows account is disabled. Her badge still opened HR this morning — I walked her out Friday. Disable the badge. Do not re-enable the AD account.", hoursAgo(2))],
      }),
    ],
  };
}

export function seedSoc() {
  return {
    alerts: [
      { id: "ALT-91", host: "NW-WS-3304", rule: "Mass file rename / ransom note", sev: "high", status: "open" },
      { id: "ALT-88", host: "NW-WS-1042", rule: "Failed logon burst (lockout)", sev: "med", status: "open" },
      { id: "ALT-77", host: "NW-LT-0007", rule: "Macro from unknown sender", sev: "med", status: "open" },
    ],
    tickets: [
      baseTicket({
        id: "SOC-3001",
        desk: "soc",
        subject: "ALT-91 ransom note on Kenji's workstation",
        preview: "EDR: README_RESTORE.txt and mass rename on NW-WS-3304.",
        caller: { name: "EDR", sam: "kmori", host: "NW-WS-3304" },
        channel: "email",
        priority: "p1",
        category: "endpoint",
        skills: ["tickets", "soc"],
        required: ["verify:kmori", "isolate:NW-WS-3304"],
        createdAt: minutesAgo(9),
        slaMin: 20,
        messages: [msg("EDR", "user", "NW-WS-3304: 400+ file extensions changed, ransom note on the desktop. Isolate. Do not power off until memory is captured — isolation is enough for Tier-1.", minutesAgo(9))],
      }),
      baseTicket({
        id: "SOC-3002",
        desk: "soc",
        subject: "Failed logon burst on jlee — attack or lockout?",
        preview: "Same timestamps as Jordan's help-desk lockout.",
        caller: { name: "SIEM", sam: "jlee", host: "NW-WS-1042" },
        channel: "email",
        priority: "p2",
        category: "identity",
        skills: ["tickets", "soc", "escalation"],
        required: ["verify:jlee", "falsepos:ALT-88"],
        escalate: false,
        createdAt: minutesAgo(30),
        messages: [msg("SIEM", "user", "12 failed logons then lockout on jlee. Help desk has a live ticket. If this is the user fat-fingering, close as false positive. If source IP is off-site, isolate and escalate.", minutesAgo(30))],
      }),
      baseTicket({
        id: "SOC-3003",
        desk: "soc",
        subject: "VIP opened a macro from 'Board-Packet.zip'",
        preview: "Riley's laptop. Macro enabled. Beacon not yet confirmed.",
        caller: { name: "Riley Cho", sam: "rcho", host: "NW-LT-0007" },
        channel: "voice",
        priority: "p1",
        skills: ["tickets", "soc"],
        required: ["verify:rcho", "isolate:NW-LT-0007"],
        createdAt: minutesAgo(15),
        slaMin: 25,
        messages: [msg("Riley Cho", "user", "I opened the board packet from email. Outlook yelled. Is my laptop fine? I have a meeting in ten minutes — do not take it if you don't have to.", minutesAgo(15))],
      }),
    ],
  };
}

export function seedNoc() {
  return {
    circuits: [
      { id: "CIR-WH", name: "Warehouse uplink", site: "WH", state: "down", latency: "—", loss: "100%" },
      { id: "CIR-HQ", name: "HQ DIA", site: "HQ", state: "up", latency: "9ms", loss: "0%" },
      { id: "CIR-AZ", name: "Azure ExpressRoute", site: "WAN", state: "degraded", latency: "240ms", loss: "4%" },
    ],
    tickets: [
      baseTicket({
        id: "NOC-4001",
        desk: "noc",
        subject: "Warehouse site offline",
        preview: "CIR-WH down. Scanners and labels dead.",
        caller: { name: "Chris Dalton", sam: "cdalt", host: "CIR-WH" },
        channel: "voice",
        priority: "p1",
        skills: ["tickets", "noc"],
        required: ["verify:cdalt", "bounce:CIR-WH"],
        createdAt: minutesAgo(12),
        slaMin: 30,
        messages: [msg("Chris Dalton", "user", "Whole warehouse dropped. Phones on LTE. Bounce the uplink before you drive out here.", minutesAgo(12))],
      }),
      baseTicket({
        id: "NOC-4002",
        desk: "noc",
        subject: "Azure latency — app timeouts",
        preview: "ExpressRoute 240ms / 4% loss. Not a bounce-and-hope.",
        caller: { name: "Priya Nair", sam: "pnair", host: "CIR-AZ" },
        channel: "chat",
        priority: "p2",
        skills: ["tickets", "noc", "escalation"],
        required: ["verify:pnair", "escalate:NOC-4002"],
        escalate: true,
        createdAt: hoursAgo(1),
        slaMin: 90,
        messages: [msg("Priya Nair", "user", "API calls to Azure SQL are dying. Don't bounce ExpressRoute. Open a carrier ticket — this needs WAN, not a reboot.", hoursAgo(1))],
      }),
    ],
  };
}

export function seedDba() {
  return {
    sessions: [
      { spid: 88, db: "Northwind", user: "web-prod", wait: "LCK_M_X", blocking: true, sql: "UPDATE Orders SET ..." },
      { spid: 91, db: "Northwind", user: "report-bot", wait: "LCK_M_S", blocking: false, sql: "SELECT * FROM Orders" },
      { spid: 12, db: "Northwind", user: "sa", wait: "RUNNING", blocking: false, sql: "BACKUP DATABASE" },
    ],
    jobs: [
      { id: "JOB-NIGHT", name: "Nightly ETL", last: "Failed", step: "Load warehouse" },
      { id: "JOB-IDX", name: "Index rebuild", last: "Succeeded", step: "—" },
    ],
    tickets: [
      baseTicket({
        id: "DBA-5001",
        desk: "dba",
        subject: "Orders page spinning — blocking session",
        preview: "SPID 88 holding LCK_M_X. Reports piled up behind it.",
        caller: { name: "Priya Nair", sam: "pnair", host: "NW-SQL-01" },
        channel: "chat",
        priority: "p1",
        skills: ["tickets", "dba"],
        required: ["verify:pnair", "kill:88"],
        createdAt: minutesAgo(11),
        slaMin: 25,
        messages: [msg("Priya Nair", "user", "Checkout is hung. Looks like a blocked update on Orders. Kill the blocker if it's a runaway session — don't restart SQL.", minutesAgo(11))],
      }),
      baseTicket({
        id: "DBA-5002",
        desk: "dba",
        subject: "Nightly ETL failed",
        preview: "JOB-NIGHT failed at Load warehouse. Shipping needs today's file.",
        caller: { name: "Chris Dalton", sam: "cdalt", host: "JOB-NIGHT" },
        channel: "email",
        priority: "p2",
        skills: ["tickets", "dba"],
        required: ["verify:cdalt", "rerun:JOB-NIGHT"],
        createdAt: hoursAgo(4),
        slaMin: 180,
        messages: [msg("Chris Dalton", "user", "Morning file never landed. Job says failed. Rerun ETL. If it fails again, escalate — I don't want you editing SSIS.", hoursAgo(4))],
      }),
      baseTicket({
        id: "DBA-5003",
        desk: "dba",
        subject: "App is slow — they want an index today",
        preview: "Missing index on Orders.ShipDate. Not a help-desk click.",
        caller: { name: "Kenji Mori", sam: "kmori", host: "NW-SQL-01" },
        channel: "chat",
        priority: "p3",
        skills: ["tickets", "dba", "escalation"],
        required: ["verify:kmori", "escalate:DBA-5003"],
        escalate: true,
        createdAt: hoursAgo(5),
        slaMin: 480,
        messages: [msg("Kenji Mori", "user", "Can you add an index on ShipDate real quick? Query store says that's the wait. I know that's a change — just checking.", hoursAgo(5))],
      }),
      baseTicket({
        id: "DBA-5004",
        desk: "dba",
        subject: "Prove the blocker with a query — then kill it",
        preview: "Don't click Kill until you can show who is blocking.",
        caller: { name: "Priya Nair", sam: "pnair", host: "NW-SQL-01" },
        channel: "chat",
        priority: "p1",
        skills: ["tickets", "dba", "sql"],
        required: ["verify:pnair", "sql:who", "kill:88"],
        createdAt: minutesAgo(7),
        slaMin: 30,
        messages: [msg("Priya Nair", "user", "Same checkout hang. This time they want the query in the ticket. sp_who2 or SELECT blocking sessions. Then KILL 88. Do not CREATE INDEX.", minutesAgo(7))],
      }),
    ],
  };
}

export function seedChange() {
  return {
    tickets: [
      baseTicket({
        id: "CHG-6001",
        desk: "change",
        subject: "Standard: open 443 from partner /32 on sg-web",
        preview: "Partner IP 203.0.113.19. Backout: remove the rule.",
        caller: { name: "Luis Ortega", sam: "lortega", host: "sg-web" },
        channel: "email",
        priority: "p3",
        skills: ["tickets", "change"],
        required: ["verify:lortega", "approve:CHG-6001"],
        createdAt: hoursAgo(6),
        slaMin: 480,
        messages: [msg("Luis Ortega", "user", "Standard change. Partner needs 443 only from 203.0.113.19. Backout is delete the SG rule. Window Saturday 02:00. Approve if it looks standard.", hoursAgo(6))],
      }),
      baseTicket({
        id: "CHG-6002",
        desk: "change",
        subject: "DC patch this Friday with no backout",
        preview: "Domain controller cumulative update. Rollback: 'reboot if it breaks.'",
        caller: { name: "Kenji Mori", sam: "kmori", host: "NW-DC-01" },
        channel: "email",
        priority: "p2",
        skills: ["tickets", "change", "escalation"],
        required: ["verify:kmori", "reject:CHG-6002"],
        escalate: false,
        createdAt: hoursAgo(2),
        slaMin: 240,
        messages: [msg("Kenji Mori", "user", "Need CAB for DC patch Friday night. If it fails we'll just reboot. Snapshot? We don't snapshot DCs. Approve so I can start.", hoursAgo(2))],
      }),
    ],
  };
}

export function seedStig() {
  return {
    telnet: true,
    guestAdmin: true,
    neverExpire: true,
    tickets: [
      baseTicket({
        id: "STG-7001",
        desk: "stig",
        subject: "CAT I — Telnet still listening on the file server",
        preview: "Lab control V-LAB-TELNET. NW-FS-01. Disable the service.",
        caller: { name: "Luis Ortega", sam: "lortega", host: "NW-FS-01" },
        channel: "email",
        priority: "p1",
        skills: ["tickets", "stig", "windows"],
        required: ["verify:lortega", "stigfix:telnet"],
        createdAt: minutesAgo(20),
        slaMin: 60,
        messages: [msg("Luis Ortega", "user", "Weekly STIG-style checklist: Telnet is still running on NW-FS-01. Disable it. This is a lab control, not a live DISA scan.", minutesAgo(20))],
      }),
      baseTicket({
        id: "STG-7002",
        desk: "stig",
        subject: "Guest is in local Administrators on Kenji's PC",
        preview: "V-LAB-ADMIN. Remove Guest from Administrators.",
        caller: { name: "Kenji Mori", sam: "kmori", host: "NW-WS-3304" },
        channel: "chat",
        priority: "p1",
        skills: ["tickets", "stig", "windows"],
        required: ["verify:kmori", "stigfix:guest"],
        createdAt: minutesAgo(35),
        slaMin: 90,
        messages: [msg("Kenji Mori", "user", "Audit finding: Guest is in Administrators on my workstation. Please remove it. Don't add me to Domain Admins to 'make it easier.'", minutesAgo(35))],
      }),
      baseTicket({
        id: "STG-7003",
        desk: "stig",
        subject: "Password never expires on the batch account",
        preview: "V-LAB-PEXPIRE. Clear the never-expire flag. CAT II.",
        caller: { name: "Luis Ortega", sam: "lortega", host: "NW-DC-01" },
        channel: "email",
        priority: "p2",
        skills: ["tickets", "stig", "ad"],
        required: ["verify:lortega", "stigfix:expire"],
        createdAt: hoursAgo(2),
        slaMin: 240,
        messages: [msg("Luis Ortega", "user", "batch-nw is set to password never expires. That's a finding. Clear the flag. Don't reset the password in email.", hoursAgo(2))],
      }),
      baseTicket({
        id: "STG-7004",
        desk: "stig",
        subject: "STIGing the domain controller this afternoon",
        preview: "No window, no backup, 'just run the checklist on NW-DC-01.'",
        caller: { name: "Kenji Mori", sam: "kmori", host: "NW-DC-01" },
        channel: "chat",
        priority: "p2",
        skills: ["tickets", "stig", "escalation"],
        required: ["verify:kmori", "escalate:STG-7004"],
        escalate: true,
        createdAt: hoursAgo(1),
        slaMin: 120,
        messages: [msg("Kenji Mori", "user", "Can you STIG the DC before standup? I'll watch. No change ticket. If it breaks we reboot.", hoursAgo(1))],
      }),
    ],
  };
}

export function seedPcap() {
  return {
    frames: [
      { id: 1, time: "0.001", src: "10.40.2.18", dst: "8.8.8.8", proto: "DNS", info: "Query A nw-fs-01.northwind.corp → public resolver", tag: "dns" },
      { id: 2, time: "0.044", src: "8.8.8.8", dst: "10.40.2.18", proto: "DNS", info: "No such name (corp zone unknown to 8.8.8.8)", tag: "dns" },
      { id: 3, time: "0.200", src: "10.40.2.18", dst: "10.20.0.20", proto: "SMB", info: "Negotiate Protocol — no reply", tag: "dns" },
      { id: 4, time: "1.010", src: "10.20.8.81", dst: "10.20.0.50", proto: "HTTP", info: "GET /login  Authorization: Basic bHVpczpXZWFrUGFzcw==", tag: "clear" },
      { id: 5, time: "1.012", src: "10.20.0.50", dst: "10.20.8.81", proto: "HTTP", info: "200 OK  Set-Cookie: session=…", tag: "clear" },
      { id: 6, time: "2.100", src: "10.20.33.4", dst: "10.20.0.11", proto: "TCP", info: "SYN  22", tag: "scan" },
      { id: 7, time: "2.101", src: "10.20.33.4", dst: "10.20.0.11", proto: "TCP", info: "SYN  80", tag: "scan" },
      { id: 8, time: "2.102", src: "10.20.33.4", dst: "10.20.0.11", proto: "TCP", info: "SYN  135", tag: "scan" },
      { id: 9, time: "2.103", src: "10.20.33.4", dst: "10.20.0.11", proto: "TCP", info: "SYN  445", tag: "scan" },
      { id: 10, time: "2.104", src: "10.20.33.4", dst: "10.20.0.11", proto: "TCP", info: "SYN  3389", tag: "scan" },
      { id: 11, time: "3.400", src: "10.60.1.14", dst: "255.255.255.255", proto: "DHCP", info: "Discover — no Offer on the wire", tag: "dhcp" },
      { id: 12, time: "8.000", src: "10.20.4.42", dst: "10.20.0.11", proto: "Kerberos", info: "AS-REQ jlee  (failed preauth — matches lockout)", tag: "noise" },
    ],
    tickets: [
      baseTicket({
        id: "CAP-8001",
        desk: "pcap",
        subject: "Warehouse share dead — we spanned the switch",
        preview: "Capture from Chris's VLAN. Find why \\\\nw-fs-01 fails.",
        caller: { name: "Chris Dalton", sam: "cdalt", host: "NW-WS-2218" },
        channel: "email",
        priority: "p2",
        skills: ["tickets", "pcap", "network"],
        required: ["verify:cdalt", "pcapfind:dns"],
        createdAt: minutesAgo(18),
        slaMin: 90,
        messages: [msg("Chris Dalton", "user", "Same share problem. Networking dropped a span. Look at the capture before you drive to the warehouse.", minutesAgo(18))],
      }),
      baseTicket({
        id: "CAP-8002",
        desk: "pcap",
        subject: "HR site login visible in the clear",
        preview: "HTTP Basic on the wire. Do not 'just turn off HTTPS.'",
        caller: { name: "Hannah Brooks", sam: "hbrooks", host: "NW-WS-0881" },
        channel: "chat",
        priority: "p2",
        skills: ["tickets", "pcap", "escalation"],
        required: ["verify:hbrooks", "pcapfind:clear", "escalate:CAP-8002"],
        escalate: true,
        createdAt: hoursAgo(1),
        slaMin: 180,
        messages: [msg("Hannah Brooks", "user", "Someone said they can see my password in Wireshark on the HR login. Fix the site today? I don't write apps.", hoursAgo(1))],
      }),
      baseTicket({
        id: "CAP-8003",
        desk: "pcap",
        subject: "SYN flood looking at the DC",
        preview: "Many SYNs from Kenji's PC to NW-DC-01. Isolate, don't 'reset the NIC.'",
        caller: { name: "EDR", sam: "kmori", host: "NW-WS-3304" },
        channel: "email",
        priority: "p1",
        skills: ["tickets", "pcap", "soc"],
        required: ["verify:kmori", "pcapfind:scan", "isolate:NW-WS-3304"],
        createdAt: minutesAgo(8),
        slaMin: 25,
        messages: [msg("EDR", "user", "Capture shows a port sweep from NW-WS-3304 at the DC. Isolate that host. Don't reboot it 'to clear the scan.'", minutesAgo(8))],
      }),
      baseTicket({
        id: "CAP-8004",
        desk: "pcap",
        subject: "Clinic PC — Discover, no Offer",
        preview: "Harbor front desk. DHCP on the wire, no server answer.",
        caller: { name: "Maya Chen", sam: "mchen", host: "HD-WS-14" },
        channel: "voice",
        priority: "p2",
        skills: ["tickets", "pcap", "network"],
        required: ["verify:mchen", "pcapfind:dhcp"],
        createdAt: minutesAgo(14),
        slaMin: 50,
        messages: [msg("Maya Chen", "user", "You already talked DHCP. The capture is here. I still have no Offer. Don't bounce the HQ circuit.", minutesAgo(14))],
      }),
    ],
  };
}

export const LAB_KB = [
  { id: "kb-cld-key", category: "Cloud", title: "Leaked access key", body: "Disable the leaked key immediately. Do not paste a new secret in chat. Rotation happens in secrets manager after the old key is dead." },
  { id: "kb-cld-sg", category: "Cloud", title: "SSH from the internet", body: "Port 22 on 0.0.0.0/0 is an audit fail. Restrict to 10.20.0.0/16 or the bastion security group. HTTPS 443 to the world can stay." },
  { id: "kb-acs", category: "Access", title: "Badge vs AD", body: "Disabling a Windows account does not kill a badge. Terminations need the badge disabled in the access system. Grant only the door they asked for." },
  { id: "kb-soc", category: "SOC", title: "Isolate vs false positive", body: "Ransomware and unknown macros: isolate the host. A failed-logon burst that matches a live help-desk lockout is usually a false positive — do not isolate the AP clerk. Never Release NAC on an isolated ransom host (NW-WS-3304) — escalate INC-2522." },
  { id: "kb-noc", category: "NOC", title: "Bounce vs carrier", body: "A dead site uplink can be bounced. ExpressRoute / DIA degradation with loss is a carrier ticket — do not bounce it." },
  { id: "kb-dba", category: "DBA", title: "Kill vs schema", body: "Kill a blocking runaway SPID. Rerun a failed ETL. Do not add indexes from the help desk — that is a change. Use the SQL box: sp_who2, then KILL 88." },
  { id: "kb-chg", category: "Change", title: "Standard vs reckless", body: "Approve a standard SG rule with a /32, a backout, and a window. Reject a DC patch with no snapshot and 'reboot if it breaks' as rollback." },
  { id: "kb-stig", category: "STIG", title: "Lab STIGs vs a live enclave", body: "These are STIG-style lab controls (Telnet off, Guest out of Administrators, password expiration). Disable the insecure service. Do not STIG a domain controller with no window. Never claim a DISA SCAP of a real network on a resume." },
  { id: "kb-pcap", category: "Capture", title: "Read the packets, then act", body: "Filter DNS / HTTP / TCP / DHCP. Public DNS (8.8.8.8) explains a dead corp share. HTTP Basic is an app-team escalate. A SYN sweep at the DC is isolate. DHCP Discover with no Offer is the lease — not a WAN bounce." },
];

export const DESK_META = [
  { id: "queue", name: "Help desk", blurb: "MSP queue. Six clients. Claim, identity, AD, vault, RDP." },
  { id: "cloud", name: "Cloud", blurb: "One case at a time: start a VM, kill a leaked key, or lock SSH." },
  { id: "access", name: "Access", blurb: "Badges, doors, controllers." },
  { id: "soc", name: "SOC", blurb: "Alerts, isolate, false positive." },
  { id: "noc", name: "NOC", blurb: "Circuits, bounce vs escalate WAN." },
  { id: "dba", name: "DBA", blurb: "Blocking SPIDs, SQL jobs, query window." },
  { id: "change", name: "Change", blurb: "Approve standard. Reject reckless." },
  { id: "stig", name: "STIG", blurb: "Lab controls. CAT I/II. Don't STIG the DC." },
  { id: "pcap", name: "Capture", blurb: "Simulated packets. Find the frame, then act." },
];
